enabled: true

rules:
  ignore_paths:
    value:
      - vendor/**/*
      - lib/assets/**/*

  line_length:
    value: 80

  string_literals:
    value: double_quotes
    options:
      - single_quotes
      - double_quotes

  hash_syntax:
    value: new
    options:
      - new
      - hash_rockets


  collection_methods:
    value:
      collect: map
      reduce: inject
      find: detect
      find_all: select
    options:
      map:
        - map
        - collect
      reduce:
        - reduce
        - inject
      find:
        - find
        - detect
      filter:
        - find_all
